{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/07_24_2025/backtests_package/VolatilityCorridorPutter_PKG.py:99: UserWarning: Some prices are larger than initial cash value. Note that fractional trading is not supported. If you want to trade Bitcoin, increase initial cash, or trade \u03bcBTC or satoshis instead (GH-134).\n  bt = Backtest(data, VolatilityCorridorPutter, commission=.002, margin=1, trade_on_close=True)\n/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/07_24_2025/backtests_package/VolatilityCorridorPutter_PKG.py:99: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.\n  bt = Backtest(data, VolatilityCorridorPutter, commission=.002, margin=1, trade_on_close=True)\nTraceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/07_24_2025/backtests_package/VolatilityCorridorPutter_PKG.py\", line 100, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1139, in run\n    strategy.init()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/07_24_2025/backtests_package/VolatilityCorridorPutter_PKG.py\", line 9, in init\n    self.data.columns = self.data.columns.str.strip().str.lower()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/_util.py\", line 125, in __getattr__\n    raise AttributeError(f\"Column '{item}' not in data\") from None\nAttributeError: Column 'columns' not in data\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v2/07_24_2025/backtests_package/VolatilityCorridorPutter_PKG.py` failed. (See above for error)\n",
  "execution_time": 1.109849,
  "timestamp": "2025-07-24T10:48:35.748350"
}