{
  "success": false,
  "return_code": 1,
  "stdout": "\ud83c\udf19 Moon Dev: Initialized DifferentialCrossover Strategy \u2728\n\ud83c\udf19 Moon Dev: Potential entry signal at 16854.21 \ud83d\ude80\n\n",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_final/DifferentialCrossover_BTFinal_v3.py\", line 125, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_final/DifferentialCrossover_BTFinal_v3.py\", line 107, in next\n    equity = self._broker.get_equity()\nAttributeError: '_Broker' object has no attribute 'get_equity'. Did you mean: '_equity'?\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_final/DifferentialCrossover_BTFinal_v3.py` failed. (See above for error)\n",
  "execution_time": 1.016951,
  "timestamp": "2025-10-20T11:22:50.200791"
}